spring.application.name=user-service
server.port=${SERVER_PORT:8081}
# === Postgres ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_service}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
# === Liquibase ===
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:none}
logging.level.liquibase=info
# === Redis ===
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}  # ????? ?? ?????????
spring.data.redis.timeout=${SPRING_DATA_REDIS_TIMEOUT:2s}
spring.cache.type=redis
# change!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

spring.cache.redis.time-to-live=${CACHE_TTL:10m}
spring.cache.redis.cache-null-values=${CACHE_CACHE_NULL_VALUES:false}
spring.data.redis.repositories.enabled=${SPRING_DATA_REDIS_REPOSITORIES_ENABLED:false}
# logging
logging.level.org.springframework.cache=TRACE
